---
- name: Password Change - Ensure DB admin's password is defined.
  shell: >
    mysql -u root -NBe
    "ALTER USER '{{ mysql_db_admin_user }}'@'localhost'
    IDENTIFIED BY '{{ __mysql_db_admin_password }}'; FLUSH PRIVILEGES;"
  tags: skip_ansible_lint

- name: Password Change - Ensure root's my.cnf is installed.
  template:
    src: "root-my.cnf.j2"
    dest: "{{ __mysql_root_home }}/.my.cnf"
    owner: "{{ __mysql_root_user }}"
    group: "{{ __mysql_root_group }}"
    mode: 0600
